// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSE3j_FHaJxsu453YgOq55-f4IZfytMfw',
    appId: '1:346704774165:web:f72636daa029a1f3a67a1c',
    messagingSenderId: '346704774165',
    projectId: 'newp-60d76',
    authDomain: 'newp-60d76.firebaseapp.com',
    storageBucket: 'newp-60d76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPZ9iUuBV0IRFEtxjfT5pmQEzjlwhEOCE',
    appId: '1:346704774165:android:5137a74e2f2ed72aa67a1c',
    messagingSenderId: '346704774165',
    projectId: 'newp-60d76',
    storageBucket: 'newp-60d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZsRv7N5Z48QF7kVvxVWnoZgu18zOWi2A',
    appId: '1:346704774165:ios:feadd18c90522be6a67a1c',
    messagingSenderId: '346704774165',
    projectId: 'newp-60d76',
    storageBucket: 'newp-60d76.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZsRv7N5Z48QF7kVvxVWnoZgu18zOWi2A',
    appId: '1:346704774165:ios:adc7ca348132bf53a67a1c',
    messagingSenderId: '346704774165',
    projectId: 'newp-60d76',
    storageBucket: 'newp-60d76.appspot.com',
    iosBundleId: 'com.example.newproject.RunnerTests',
  );
}
